<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>winexe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>_9._SimpleVideoPlayer</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FFmpegDotNet" Version="8.1.2.11" />
    <PackageReference Include="FFmpegDotNet.bin.winx64" Version="8.1.2.6" />
    <PackageReference Include="FFmpegDotNet.Skia" Version="2.3.0" />
    <PackageReference Include="NAudio" Version="3.0.1" />
    <PackageReference Include="NAudio.Wasapi" Version="3.0.1" />
    <PackageReference Include="SkiaSharp.Views.WPF" Version="4.151.1" />
  </ItemGroup>

</Project>
